In [1]:
# Ячейка 1 — Загрузка
import pandas as pd

df = pd.read_csv('user_music_listen_data.csv')
df.head()

,User_ID,T_Swift,Drake,Queen,The_Weeknd,Eminem,Nirvana,Ed_Sheeran,T_Scott,Linkin_Park,Dua_Lipa,K_Lamar,Imag_Dragons,Ariana_G
0,User_1001,53.0,0.0,87.0,102.0,0.0,92.0,112.0,79.0,64.0,0.0,49.0,212.0,112.0
1,User_1002,144.0,NaN,53.0,194.0,31.0,44.0,150.0,47.0,45.0,213.0,47.0,232.0,157.0
2,User_1003,182.0,47.0,64.0,203.0,75.0,44.0,213.0,93.0,19.0,180.0,103.0,199.0,176.0
3,User_1004,136.0,45.0,0.0,97.0,40.0,0.0,NaN,62.0,15.0,105.0,73.0,190.0,111.0
4,User_1005,110.0,33.0,52.0,127.0,51.0,23.0,57.0,0.0,0.0,98.0,66.0,124.0,66.0

In [2]:
# Ячейка 2 — Mean (среднее кол-во прослушиваний по каждому артисту)
df.drop(columns='User_ID').mean().round(2)

T_Swift          60.33
Drake            60.15
Queen            68.92
The_Weeknd      114.53
Eminem           63.87
Nirvana          59.95
Ed_Sheeran       80.13
T_Scott          61.19
Linkin_Park      66.73
Dua_Lipa         73.45
K_Lamar          74.96
Imag_Dragons    159.34
Ariana_G         66.46
dtype: float64

In [3]:
# Ячейка 3 — Median (медиана прослушиваний)
df.drop(columns='User_ID').median().round(2)

T_Swift          46.0
Drake            46.0
Queen            63.0
The_Weeknd      110.0
Eminem           58.0
Nirvana          55.0
Ed_Sheeran       71.0
T_Scott          51.0
Linkin_Park      62.0
Dua_Lipa         72.0
K_Lamar          66.0
Imag_Dragons    158.0
Ariana_G         59.0
dtype: float64

In [4]:
# Ячейка 4 — Mode (самое частое кол-во прослушиваний)
df.drop(columns='User_ID').mode().iloc[0].round(2)

T_Swift         0.0
Drake           0.0
Queen           0.0
The_Weeknd      0.0
Eminem          0.0
Nirvana         0.0
Ed_Sheeran      0.0
T_Scott         0.0
Linkin_Park     0.0
Dua_Lipa        0.0
K_Lamar         0.0
Imag_Dragons    0.0
Ariana_G        0.0
Name: 0, dtype: float64

In [5]:
# Ячейка 5 — Всё сразу в одной таблице
stats = pd.DataFrame({
    'Mean':   df.drop(columns='User_ID').mean().round(2),
    'Median': df.drop(columns='User_ID').median().round(2),
    'Mode':   df.drop(columns='User_ID').mode().iloc[0].round(2)
})

stats

                Mean  Median  Mode
T_Swift        60.33    46.0   0.0
Drake          60.15    46.0   0.0
Queen          68.92    63.0   0.0
The_Weeknd    114.53   110.0   0.0
Eminem         63.87    58.0   0.0
Nirvana        59.95    55.0   0.0
Ed_Sheeran     80.13    71.0   0.0
T_Scott        61.19    51.0   0.0
Linkin_Park    66.73    62.0   0.0
Dua_Lipa       73.45    72.0   0.0
K_Lamar        74.96    66.0   0.0
Imag_Dragons  159.34   158.0   0.0
Ariana_G       66.46    59.0   0.0